name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: unbuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24.18.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check build
        run: |
          if [ ! -d "dist" ]; then
            echo "Le dossier dist/ n'existe pas"
            exit 1
          fi

          echo "Le build a été généré avec succès."
          ls -l dist/
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/

      - name: Build Summary
        if: always()
        run: |
          echo "## Build Summary" >> "$GITHUB_STEP_SUMMARY"
          echo "Status: ${{ job.status }}" >> "$GITHUB_STEP_SUMMARY"
          echo "Commit: $GITHUB_SHA" >> "$GITHUB_STEP_SUMMARY"